// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Proyecto2.Model;

public partial class Artista
{
    [Key]
    public int Id { get; set; }

    public int Usuario { get; set; }

    [Required]
    [StringLength(100)]
    [Unicode(false)]
    public string Nombre { get; set; }

    [Required]
    [StringLength(300)]
    [Unicode(false)]
    public string Informacion { get; set; }

    [Required]
    [StringLength(300)]
    [Unicode(false)]
    public string Estilo { get; set; }

    [Required]
    [StringLength(300)]
    [Unicode(false)]
    public string Experiencia { get; set; }

    [Required]
    [StringLength(200)]
    [Unicode(false)]
    public string Enlace { get; set; }

    public bool Eliminado { get; set; }

    [InverseProperty("ReceptorNavigation")]
    public virtual ICollection<Mensaje> Mensaje { get; set; } = new List<Mensaje>();

    [InverseProperty("ArtistaNavigation")]
    public virtual ICollection<ObraArte> ObraArte { get; set; } = new List<ObraArte>();

    [ForeignKey("Usuario")]
    [InverseProperty("Artista")]
    public virtual Usuario UsuarioNavigation { get; set; }
}