// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Proyecto2.Model;

public partial class CategoriaObra
{
    [Key]
    public int Id { get; set; }

    [Required]
    [StringLength(100)]
    [Unicode(false)]
    public string Descripcion { get; set; }

    public bool Eliminado { get; set; }

    [InverseProperty("CategoriaObraNavigation")]
    public virtual ICollection<ObraArte> ObraArte { get; set; } = new List<ObraArte>();
}