// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Proyecto2.Model;

public partial class ConfiguracionApp
{
    [Key]
    public int Id { get; set; }

    [Column(TypeName = "decimal(22, 2)")]
    public decimal LimiteMaximoPuja { get; set; }

    public bool Eliminado { get; set; }
}