// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Proyecto2.Model;

public partial class DimensionObra
{
    [Key]
    public int Id { get; set; }

    public int ObraArte { get; set; }

    [Column(TypeName = "decimal(5, 2)")]
    public decimal Altura { get; set; }

    [Column(TypeName = "decimal(5, 2)")]
    public decimal Ancho { get; set; }

    [Column(TypeName = "decimal(5, 2)")]
    public decimal Profundidad { get; set; }

    public bool Eliminado { get; set; }

    [ForeignKey("ObraArte")]
    [InverseProperty("DimensionObra")]
    public virtual ObraArte ObraArteNavigation { get; set; }
}