// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Proyecto2.Model;

public partial class ImagenObra
{
    [Key]
    public int Id { get; set; }

    public int ObraArte { get; set; }

    [Required]
    [Unicode(false)]
    public string Imagen { get; set; }

    public bool Eliminado { get; set; }

    [ForeignKey("ObraArte")]
    [InverseProperty("ImagenObra")]
    public virtual ObraArte ObraArteNavigation { get; set; }
}