// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Proyecto2.Model;

public partial class Mensaje
{
    [Key]
    public int Id { get; set; }

    public int Subasta { get; set; }

    public int? Emisor { get; set; }

    public int? Receptor { get; set; }

    [Column("Mensaje")]
    [StringLength(500)]
    [Unicode(false)]
    public string Mensaje1 { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime Fecha { get; set; }

    public bool Eliminado { get; set; }

    [ForeignKey("Emisor")]
    [InverseProperty("Mensaje")]
    public virtual Usuario EmisorNavigation { get; set; }

    [ForeignKey("Receptor")]
    [InverseProperty("Mensaje")]
    public virtual Artista ReceptorNavigation { get; set; }

    [ForeignKey("Subasta")]
    [InverseProperty("Mensaje")]
    public virtual Subasta SubastaNavigation { get; set; }
}