// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Proyecto2.Model;

public partial class Notificacion
{
    [Key]
    public int Id { get; set; }

    public int Usuario { get; set; }

    [Required]
    [StringLength(100)]
    [Unicode(false)]
    public string Titulo { get; set; }

    [Required]
    [StringLength(500)]
    [Unicode(false)]
    public string Descripcion { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime Fecha { get; set; }

    public bool Enviado { get; set; }

    public bool Leido { get; set; }

    public bool PorApp { get; set; }

    public bool Eliminado { get; set; }

    [StringLength(500)]
    [Unicode(false)]
    public string Error { get; set; }

    [ForeignKey("Usuario")]
    [InverseProperty("Notificacion")]
    public virtual Usuario UsuarioNavigation { get; set; }
}