// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Proyecto2.Model;

public partial class Notificacion
{
    [Key]
    public int Id { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string Correo { get; set; }

    [Required]
    [StringLength(100)]
    [Unicode(false)]
    public string Titulo { get; set; }

    [Required]
    [StringLength(500)]
    [Unicode(false)]
    public string Descripcion { get; set; }

    public bool Enviado { get; set; }

    [StringLength(500)]
    [Unicode(false)]
    public string Error { get; set; }

    public bool Eliminado { get; set; }
}