// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Proyecto2.Model;

public partial class ObraArte
{
    [Key]
    public int Id { get; set; }

    public int Artista { get; set; }

    public int CategoriaObra { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string Titulo { get; set; }

    [StringLength(500)]
    [Unicode(false)]
    public string Descripcion { get; set; }

    public bool Eliminado { get; set; }

    [ForeignKey("Artista")]
    [InverseProperty("ObraArte")]
    public virtual Artista ArtistaNavigation { get; set; }

    [ForeignKey("CategoriaObra")]
    [InverseProperty("ObraArte")]
    public virtual CategoriaObra CategoriaObraNavigation { get; set; }

    [InverseProperty("ObraArteNavigation")]
    public virtual ICollection<DimensionObra> DimensionObra { get; set; } = new List<DimensionObra>();

    [InverseProperty("ObraArteNavigation")]
    public virtual ICollection<ImagenObra> ImagenObra { get; set; } = new List<ImagenObra>();

    [InverseProperty("ObraArteNavigation")]
    public virtual ICollection<Subasta> Subasta { get; set; } = new List<Subasta>();
}