// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Proyecto2.Model;

public partial class Oferta
{
    [Key]
    public int Id { get; set; }

    public int Subasta { get; set; }

    public int Usuario { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime Fecha { get; set; }

    [Column(TypeName = "decimal(22, 2)")]
    public decimal Monto { get; set; }

    public bool Eliminado { get; set; }

    [ForeignKey("Subasta")]
    [InverseProperty("Oferta")]
    public virtual Subasta SubastaNavigation { get; set; }

    [InverseProperty("OfertaNavigation")]
    public virtual ICollection<Transaccion> Transaccion { get; set; } = new List<Transaccion>();

    [ForeignKey("Usuario")]
    [InverseProperty("Oferta")]
    public virtual Usuario UsuarioNavigation { get; set; }
}