// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Proyecto2.Model;

public partial class Subasta
{
    [Key]
    public int Id { get; set; }

    public int ObraArte { get; set; }

    [Column(TypeName = "decimal(22, 2)")]
    public decimal? PrecioInicial { get; set; }

    [Column(TypeName = "decimal(22, 2)")]
    public decimal? PrecioActual { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime FechaInicial { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime FechaCierre { get; set; }

    public bool Eliminado { get; set; }

    [InverseProperty("SubastaNavigation")]
    public virtual ICollection<Mensaje> Mensaje { get; set; } = new List<Mensaje>();

    [ForeignKey("ObraArte")]
    [InverseProperty("Subasta")]
    public virtual ObraArte ObraArteNavigation { get; set; }

    [InverseProperty("SubastaNavigation")]
    public virtual ICollection<Oferta> Oferta { get; set; } = new List<Oferta>();
}