// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Proyecto2.Model;

public partial class Transaccion
{
    [Key]
    public int Id { get; set; }

    public int Usuario { get; set; }

    public int Subasta { get; set; }

    public int Oferta { get; set; }

    [Required]
    [StringLength(18)]
    [Unicode(false)]
    public string Tarjeta { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime Fecha { get; set; }

    public bool Eliminado { get; set; }

    [ForeignKey("Oferta")]
    [InverseProperty("Transaccion")]
    public virtual Oferta OfertaNavigation { get; set; }

    [ForeignKey("Subasta")]
    [InverseProperty("Transaccion")]
    public virtual Subasta SubastaNavigation { get; set; }

    [ForeignKey("Usuario")]
    [InverseProperty("Transaccion")]
    public virtual Usuario UsuarioNavigation { get; set; }
}