// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Proyecto2.Model;

public partial class Usuario
{
    [Key]
    public int Id { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string NombreUsuario { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string Correo { get; set; }

    [Required]
    [StringLength(200)]
    [Unicode(false)]
    public string Contrasena { get; set; }

    public int TipoUsuario { get; set; }

    [Unicode(false)]
    public string Foto { get; set; }

    public bool Eliminado { get; set; }

    [InverseProperty("UsuarioNavigation")]
    public virtual ICollection<Artista> Artista { get; set; } = new List<Artista>();

    [InverseProperty("EmisorNavigation")]
    public virtual ICollection<Mensaje> Mensaje { get; set; } = new List<Mensaje>();

    [InverseProperty("UsuarioNavigation")]
    public virtual ICollection<Oferta> Oferta { get; set; } = new List<Oferta>();

    [ForeignKey("TipoUsuario")]
    [InverseProperty("Usuario")]
    public virtual TipoUsuario TipoUsuarioNavigation { get; set; }

    [InverseProperty("UsuarioNavigation")]
    public virtual ICollection<Transaccion> Transaccion { get; set; } = new List<Transaccion>();
}